#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-auto-config-consistency.fullname" . }}-frontend
  labels:
    {{- include "eric-oss-auto-config-consistency-frontend.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-auto-config-consistency-frontend.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
  {{- end }}
  ports:
    - name: frontend
      port: {{ .Values.frontend.port }}
      targetPort: frontend-http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "eric-oss-auto-config-consistency.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
