CREATE TABLE eacc_executions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   job_name VARCHAR(255),
   rule_set_name VARCHAR(255),
   scope_name VARCHAR(255),
   created_by VARCHAR(255),
   execution_type VARCHAR(255),
   execution_started_at TIMESTAMP with time zone,
   consistency_audit_started_at TIMESTAMP with time zone,
   consistency_audit_ended_at TIMESTAMP with time zone,
   execution_ended_at TIMESTAMP with time zone,
   execution_status VARCHAR(255),
   total_nodes_audited INTEGER DEFAULT 0 NOT NULL,
   total_nodes_failed INTEGER DEFAULT 0 NOT NULL,
   total_mos_audited INTEGER DEFAULT 0 NOT NULL,
   total_attributes_audited INTEGER DEFAULT 0 NOT NULL,
   inconsistencies_identified INTEGER DEFAULT 0 NOT NULL,
   CONSTRAINT pk_eacc_executions PRIMARY KEY (id)
);

CREATE TABLE audit_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   managed_object_fdn VARCHAR(255),
   managed_object_type VARCHAR(255),
   attribute_name VARCHAR(255),
   current_value VARCHAR(255),
   preferred_value VARCHAR(255),
   audit_status VARCHAR(255),
   execution_id VARCHAR(255),
   rule_id VARCHAR(255),
   change_status VARCHAR(255),
   CONSTRAINT pk_audit_results PRIMARY KEY (execution_id, id)
);

CREATE TABLE job_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   job_name VARCHAR(100) NOT NULL UNIQUE,
   scope_name VARCHAR(255) NOT NULL,
   schedule VARCHAR(255) NOT NULL,
   rule_set_name VARCHAR(255) NOT NULL,
   CONSTRAINT pk_job_settings PRIMARY KEY (id)
);

CREATE TABLE rulesets (
  id BINARY(16) NOT NULL,
   name VARCHAR(255) NOT NULL UNIQUE,
   CONSTRAINT pk_rulesets PRIMARY KEY (id)
);

CREATE TABLE rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   mo_type VARCHAR(255) NULL,
   attribute_name VARCHAR(255) NULL,
   attribute_value VARCHAR(255) NULL,
   ruleset_id BINARY(16) NOT NULL,
   CONSTRAINT pk_rules PRIMARY KEY (id)
);

ALTER TABLE rules ADD CONSTRAINT FK_RULES_ON_RULESET FOREIGN KEY (ruleset_id) REFERENCES rulesets (id);

CREATE TABLE fdns (
  fdn_id BINARY(16) NOT NULL,
   fdns TEXT NOT NULL
);

CREATE TABLE scopes (
  id BINARY(16) NOT NULL,
   name VARCHAR(255) NOT NULL UNIQUE,
   CONSTRAINT pk_scopes PRIMARY KEY (id)
);

ALTER TABLE fdns ADD CONSTRAINT fk_fdns_on_scope FOREIGN KEY (fdn_id) REFERENCES scopes (id);